export class XSMRuntime {
  public static getRuntimeInit(): string[] {
    return [
      '; XSM Runtime Initialization',
      'JMP runtime_init_end',
      '',
      '; string_new: create string, R0 = address of string data, returns R0 = string handle',
      'string_new:',
      'PUSH R0',
      'PUSH R1',
      'MOV R1, R0',
      'CALL alloc',
      'POP R1',
      'POP R0',
      'RET',
      '',
      '; string_concat: R0 = left string handle, R1 = right string handle, returns R0 = new string handle',
      'string_concat:',
      'PUSH R1',
      'PUSH R2',
      'PUSH R3',
      'MOV R2, R0',
      'MOV R3, R1',
      'MOV R0, R2',
      'CALL string_len',
      'MOV R1, R0',
      'MOV R0, R3',
      'CALL string_len',
      'ADD R0, R1',
      'ADD R0, 2',
      'CALL alloc',
      'POP R3',
      'POP R2',
      'POP R1',
      'RET',
      '',
      '; string_len: R0 = string handle, returns R0 = length',
      'string_len:',
      'MOV R0, [R0]',
      'RET',
      '',
      '; object_new: creates new empty object, returns R0 = object handle',
      'object_new:',
      'PUSH R1',
      'MOV R0, 16',
      'CALL alloc',
      'MOV [R0], 0',
      'MOV [R0+1], 0',
      'POP R1',
      'RET',
      '',
      '; object_set: R0 = object handle, R1 = property index, R2 = value',
      'object_set:',
      'PUSH R3',
      'MOV R3, R0',
      'ADD R3, R1',
      'ADD R3, 2',
      'MOV [R3], R2',
      'POP R3',
      'RET',
      '',
      '; object_get: R0 = object handle, R1 = property index, returns R0 = value',
      'object_get:',
      'ADD R0, R1',
      'ADD R0, 2',
      'MOV R0, [R0]',
      'RET',
      '',
      '; array_new: creates new empty array, returns R0 = array handle',
      'array_new:',
      'PUSH R1',
      'MOV R0, 16',
      'CALL alloc',
      'MOV [R0], 0',
      'MOV [R0+1], 0',
      'POP R1',
      'RET',
      '',
      '; array_push: R0 = array handle, R1 = value',
      'array_push:',
      'PUSH R2',
      'PUSH R3',
      'MOV R2, [R0+1]',
      'ADD R2, 1',
      'MOV [R0+1], R2',
      'MOV R3, R0',
      'ADD R3, R2',
      'ADD R3, 1',
      'MOV [R3], R1',
      'POP R3',
      'POP R2',
      'RET',
      '',
      '; array_get: R0 = array handle, R1 = index, returns R0 = value',
      'array_get:',
      'ADD R0, R1',
      'ADD R0, 1',
      'MOV R0, [R0]',
      'RET',
      '',
      '; array_length: R0 = array handle, returns R0 = length',
      'array_length:',
      'MOV R0, [R0+1]',
      'RET',
      '',
      '; typeof_runtime: R0 = value, returns R0 = type string handle',
      'typeof_runtime:',
      'CMP R0, 0',
      'JZ typeof_number',
      'CMP R0, 1',
      'JZ typeof_string',
      'MOV R0, 2',
      'RET',
      'typeof_number:',
      'MOV R0, 3',
      'RET',
      'typeof_string:',
      'MOV R0, 4',
      'RET',
      '',
      '; alloc: R0 = size, returns R0 = allocated address',
      'alloc:',
      'PUSH R1',
      'MOV R1, [heap_ptr]',
      'ADD [heap_ptr], R0',
      'MOV R0, R1',
      'POP R1',
      'RET',
      '',
      'runtime_init_end:',
      'MOV [heap_ptr], 5000',
      ''
    ];
  }

  public static getStringLiteralDeclarations(): string[] {
    return [
      '; String literals will be placed here',
    ];
  }
}
